FROM knowagelabs/knowage-server-docker:7.4.8

COPY cockpitModule_mapServices.js /home/knowage/apache-tomcat/webapps/knowagecockpitengine/js/src-7.4.8/angular_1.4/cockpit/services/cockpitModule_mapServices.js